// Auto-generated by ctx.genTypes — do not edit
declare global {
    type Context = import("./$type_Context").Context;

    interface FnsRegistry {
        _test_hashline_edit: {
        nearby: typeof import("../.hyper/_test_hashline_edit/nearby").default;
        };
        cases: {
        forEdge: typeof import("./cases/forEdge").default;
        load: typeof import("./cases/load").default;
        renderDetail: typeof import("./cases/renderDetail").default;
        renderEditor: typeof import("./cases/renderEditor").default;
        renderList: typeof import("./cases/renderList").default;
        runOne: typeof import("./cases/runOne").default;
        save: typeof import("./cases/save").default;
        };
        conceptmap: {
        materialize: typeof import("./conceptmap/materialize").default;
        };
        db: {
        connect: typeof import("./db/connect").default;
        query: typeof import("./db/query").default;
        };
        etl_fhir: {
        runEdge: typeof import("./etl_fhir/runEdge").default;
        };
        fhir: {
        connect: typeof import("./fhir/connect").default;
        ensureTable: typeof import("./fhir/ensureTable").default;
        init: typeof import("./fhir/init").default;
        loadBundle: typeof import("./fhir/loadBundle").default;
        loadDir: typeof import("./fhir/loadDir").default;
        };
        http: {
        loadRoutes: typeof import("./http/loadRoutes").default;
        match: typeof import("./http/match").default;
        start: typeof import("./http/$start").default;
        };
        mapspec: {
        byResource: typeof import("./mapspec/byResource").default;
        byTable: typeof import("./mapspec/byTable").default;
        list: typeof import("./mapspec/list").default;
        loadEdges: typeof import("./mapspec/loadEdges").default;
        render: typeof import("./mapspec/render").default;
        };
        markdown: {
        highlight: typeof import("./markdown/highlight").default;
        mermaid: typeof import("./markdown/mermaid").default;
        render: typeof import("./markdown/render").default;
        };
        omop: {
        byTable: typeof import("./omop/byTable").default;
        };
        profiles: {
        byId: typeof import("./profiles/byId").default;
        compile: typeof import("./profiles/compile").default;
        load: typeof import("./profiles/load").default;
        profileForEdge: typeof import("./profiles/profileForEdge").default;
        valueSetByUrl: typeof import("./profiles/valueSetByUrl").default;
        viewForEdge: typeof import("./profiles/viewForEdge").default;
        };
        project: {
        classify: typeof import("./project/classify").default;
        roots: typeof import("./project/roots").default;
        scan: typeof import("./project/scan").default;
        };
        repl: {
        eval: typeof import("./repl/eval").default;
        load: typeof import("./repl/load").default;
        start: typeof import("./repl/$start").default;
        };
        sample: {
        renderTable: typeof import("./sample/renderTable").default;
        };
        ui_components: {
        collapsiblePanel: typeof import("./ui_components/collapsiblePanel").default;
        };
        viewdef: {
        columns: typeof import("./viewdef/columns").default;
        materialize: typeof import("./viewdef/materialize").default;
        normalize: typeof import("./viewdef/normalize").default;
        path: typeof import("./viewdef/path").default;
        run: typeof import("./viewdef/run").default;
        };
    }

    interface RootFns {
    genTypes: typeof import("./genTypes").default;
    layout: typeof import("./$layout").default;
    loadFns: typeof import("./loadFns").default;
    }

    namespace types {
        namespace omop {
            type Field = import("./omop/$type_Field").Field;
        }
        namespace profiles {
            type Profile = import("./profiles/$type_Profile").Profile;
            type ValueSet = import("./profiles/$type_ValueSet").ValueSet;
            type ViewDefinition = import("./profiles/$type_ViewDefinition").ViewDefinition;
        }
    }
}
export {};
